services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

  create-bucket:
    image: minio/mc:latest
    volumes:
      - ./create_minio_bucket.sh:/create_minio_bucket.sh
    environment:
      MC_HOST_minio: http://${MINIO_ROOT_USER}:${MINIO_ROOT_PASSWORD}@minio:9000
    entrypoint: 
      - ./create_minio_bucket.sh

  rest_app:
    build:
      context: .
      dockerfile: server/rest/Dockerfile
    container_name: rest_app
    ports:
      - "8080:8080"
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: trainer_bucket
    depends_on:
      - minio

  grpc_service:
    build:
      context: .
      dockerfile: server/grpc/Dockerfile
    container_name: grpc_service
    ports:
      - "50051:50051"
    depends_on:
      - minio

  streamlit:
    build:
      context: .
      dockerfile: gui/Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - minio
      - rest_app