FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libffi-dev \
    libssl-dev \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Установка MLflow
RUN pip install --no-cache-dir mlflow boto3 pymysql

EXPOSE ${MLFLOW_PORT}

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5001", "--backend-store-uri", "${MLFLOW_DB_PATH}", "--default-artifact-root", "${MLFLOW_ARTIFACTS_PATH}"]
