# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'model_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13model_service.proto\x12\x08modelapi\"\x07\n\x05\x45mpty\"\x80\x01\n\tModelList\x12/\n\x06models\x18\x01 \x03(\x0b\x32\x1f.modelapi.ModelList.ModelsEntry\x1a\x42\n\x0bModelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.modelapi.ModelSpec:\x02\x38\x01\"\x1f\n\tModelSpec\x12\x12\n\nparameters\x18\x01 \x03(\t\"s\n\nFeatureSet\x12\x34\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\".modelapi.FeatureSet.FeaturesEntry\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\xc4\x01\n\x0cTrainRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12:\n\nparameters\x18\x02 \x03(\x0b\x32&.modelapi.TrainRequest.ParametersEntry\x12&\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32\x14.modelapi.FeatureSet\x12\x0f\n\x07targets\x18\x04 \x03(\x01\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"C\n\rTrainResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\x08model_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_model_id\"J\n\x0ePredictRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12&\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32\x14.modelapi.FeatureSet\"8\n\x0fPredictResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x13\n\x0bpredictions\x18\x02 \x03(\x01\"!\n\rDeleteRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\" \n\x0e\x44\x65leteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8e\x02\n\x0cModelService\x12\x33\n\x0blist_models\x12\x0f.modelapi.Empty\x1a\x13.modelapi.ModelList\x12>\n\x0btrain_model\x12\x16.modelapi.TrainRequest\x1a\x17.modelapi.TrainResponse\x12\x46\n\x0fget_predictions\x12\x18.modelapi.PredictRequest\x1a\x19.modelapi.PredictResponse\x12\x41\n\x0c\x64\x65lete_model\x12\x17.modelapi.DeleteRequest\x1a\x18.modelapi.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELLIST_MODELSENTRY']._loaded_options = None
  _globals['_MODELLIST_MODELSENTRY']._serialized_options = b'8\001'
  _globals['_FEATURESET_FEATURESENTRY']._loaded_options = None
  _globals['_FEATURESET_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_TRAINREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_TRAINREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=33
  _globals['_EMPTY']._serialized_end=40
  _globals['_MODELLIST']._serialized_start=43
  _globals['_MODELLIST']._serialized_end=171
  _globals['_MODELLIST_MODELSENTRY']._serialized_start=105
  _globals['_MODELLIST_MODELSENTRY']._serialized_end=171
  _globals['_MODELSPEC']._serialized_start=173
  _globals['_MODELSPEC']._serialized_end=204
  _globals['_FEATURESET']._serialized_start=206
  _globals['_FEATURESET']._serialized_end=321
  _globals['_FEATURESET_FEATURESENTRY']._serialized_start=274
  _globals['_FEATURESET_FEATURESENTRY']._serialized_end=321
  _globals['_TRAINREQUEST']._serialized_start=324
  _globals['_TRAINREQUEST']._serialized_end=520
  _globals['_TRAINREQUEST_PARAMETERSENTRY']._serialized_start=471
  _globals['_TRAINREQUEST_PARAMETERSENTRY']._serialized_end=520
  _globals['_TRAINRESPONSE']._serialized_start=522
  _globals['_TRAINRESPONSE']._serialized_end=589
  _globals['_PREDICTREQUEST']._serialized_start=591
  _globals['_PREDICTREQUEST']._serialized_end=665
  _globals['_PREDICTRESPONSE']._serialized_start=667
  _globals['_PREDICTRESPONSE']._serialized_end=723
  _globals['_DELETEREQUEST']._serialized_start=725
  _globals['_DELETEREQUEST']._serialized_end=758
  _globals['_DELETERESPONSE']._serialized_start=760
  _globals['_DELETERESPONSE']._serialized_end=792
  _globals['_MODELSERVICE']._serialized_start=795
  _globals['_MODELSERVICE']._serialized_end=1065
# @@protoc_insertion_point(module_scope)
