# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import model_service_pb2 as model__service__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in model_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.status = channel.unary_unary(
                '/modelapi.ModelService/status',
                request_serializer=model__service__pb2.Empty.SerializeToString,
                response_deserializer=model__service__pb2.ServiceStatus.FromString,
                _registered_method=True)
        self.list_models = channel.unary_unary(
                '/modelapi.ModelService/list_models',
                request_serializer=model__service__pb2.Empty.SerializeToString,
                response_deserializer=model__service__pb2.ModelList.FromString,
                _registered_method=True)
        self.train_model = channel.unary_unary(
                '/modelapi.ModelService/train_model',
                request_serializer=model__service__pb2.TrainRequest.SerializeToString,
                response_deserializer=model__service__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.get_predictions = channel.unary_unary(
                '/modelapi.ModelService/get_predictions',
                request_serializer=model__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=model__service__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.delete_model = channel.unary_unary(
                '/modelapi.ModelService/delete_model',
                request_serializer=model__service__pb2.DeleteRequest.SerializeToString,
                response_deserializer=model__service__pb2.DeleteResponse.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list_models(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def train_model(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_predictions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_model(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'status': grpc.unary_unary_rpc_method_handler(
                    servicer.status,
                    request_deserializer=model__service__pb2.Empty.FromString,
                    response_serializer=model__service__pb2.ServiceStatus.SerializeToString,
            ),
            'list_models': grpc.unary_unary_rpc_method_handler(
                    servicer.list_models,
                    request_deserializer=model__service__pb2.Empty.FromString,
                    response_serializer=model__service__pb2.ModelList.SerializeToString,
            ),
            'train_model': grpc.unary_unary_rpc_method_handler(
                    servicer.train_model,
                    request_deserializer=model__service__pb2.TrainRequest.FromString,
                    response_serializer=model__service__pb2.TrainResponse.SerializeToString,
            ),
            'get_predictions': grpc.unary_unary_rpc_method_handler(
                    servicer.get_predictions,
                    request_deserializer=model__service__pb2.PredictRequest.FromString,
                    response_serializer=model__service__pb2.PredictResponse.SerializeToString,
            ),
            'delete_model': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_model,
                    request_deserializer=model__service__pb2.DeleteRequest.FromString,
                    response_serializer=model__service__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'modelapi.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('modelapi.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelapi.ModelService/status',
            model__service__pb2.Empty.SerializeToString,
            model__service__pb2.ServiceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def list_models(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelapi.ModelService/list_models',
            model__service__pb2.Empty.SerializeToString,
            model__service__pb2.ModelList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def train_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelapi.ModelService/train_model',
            model__service__pb2.TrainRequest.SerializeToString,
            model__service__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_predictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelapi.ModelService/get_predictions',
            model__service__pb2.PredictRequest.SerializeToString,
            model__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modelapi.ModelService/delete_model',
            model__service__pb2.DeleteRequest.SerializeToString,
            model__service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
