name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest

  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.8.4

      - name: Install dependencies
        run: poetry install

      - name: Run flake8
        run: poetry run flake8 .

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      minio:
        image: minio/minio
        options: >-
          --name minio
          --env MINIO_ACCESS_KEY=minioadmin
          --env MINIO_SECRET_KEY=minioadmin
          --env MINIO_ROOT_USER=minioadmin
          --env MINIO_ROOT_PASSWORD=minioadmin
        ports:
          - 9000:9000
        command: server /data

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.8.4

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run pytest
