name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - dev-hw3
  pull_request:
    branches:
      - main
      - master
      - dev-hw3

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops-hse-2024:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mlops-hse-2024:latest

  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.8.4

      - name: Install dependencies
        run: poetry install

      - name: Run pylint
        run: poetry run pylint .

      - name: Run pylint
        run: poetry run pylint .

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.8.4

      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: poetry run pytest unit_tests
